# Generated by Django 3.2.4 on 2021-06-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='content',
        ),
    ]
